name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@master
        


      - run: pwd

      - name: Install dependencies
        run: make install-deps

      - name: poetry run train
        run: make train