name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: cd model-template/my-model
        run: cd ./model-template/my_model/ && pwd && make install-deps && make train

